[package]
name = "panopticon"
version = "0.1.0"
authors = ["Steven Kipp <sk1pp@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipinfo = "0.1"


#this requires the openGL driver
[dependencies.iced]
git = "https://github.com/hecrj/iced.git"
features = ["glow"]
